parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
#            string_functions:
#                MATCH_AGAINST: App\Doctrine\Extension\MatchAgainst
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
            string_functions:
                field: DoctrineExtensions\Query\Mysql\Field
                collate: DoctrineExtensions\Query\Mysql\Collate
                match: DoctrineExtensions\Query\Mysql\MatchAgainst
                soundex: DoctrineExtensions\Query\Mysql\Soundex
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
                datediff: DoctrineExtensions\Query\Mysql\DateDiff
                datesub: DoctrineExtensions\Query\Mysql\DateSub
                year: DoctrineExtensions\Query\Mysql\Year
                month: DoctrineExtensions\Query\Mysql\Month
                day: DoctrineExtensions\Query\Mysql\Day
                now: DoctrineExtensions\Query\Mysql\Now
                time: DoctrineExtensions\Query\Mysql\Time
                timediff: DoctrineExtensions\Query\Mysql\TimeDiff