swoole:
    http_server:
        port: 9501
        host: localhost
        running_mode: 'process'
        socket_type: tcp
        ssl_enabled: false
        trusted_hosts: localhost,127.0.0.1
        trusted_proxies:
            - '*'
            - 127.0.0.1/8
            - 192.168.2./16
        static:
            strategy: 'advanced'
            public_dir: '%kernel.project_dir%/public'
        hmr: 'auto'
        services:
            debug_handler: false
            trust_all_proxies_handler: true
            cloudfront_proto_header_handler: true
            entity_manager_handler: true
        settings:
            worker_count: 1
            reactor_count: 1
            log_file: '%kernel.logs_dir%/swoole_%kernel.environment%.log'
            log_level: auto
            pid_file: '/var/run/swoole_http_server.pid'